### ISSUE TITLE
SQL syntax

### ISSUE THREAD

**Issue by leonrudowicz** [studyjourney/codedatasurvey#2]
It seems like it does not like your SQL syntax... 
The first error also appears as the authorization header within the graphql query, resulting in a 500 at the graphql.

I tried the request 3 times, there are 3 new student entrys in the db. One request also created the assessments. 
All were done with all checkboxes checked

```
> codedatasurvey@1.0.0 start /Users/leonmba/gitstuff/codedatasurvey
> node ./index.js

Welcome to 1.0.0!
[INFO] - Listening on port 3000
[INFO] - Connected to the MySQL server
[ERROR] -  Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3
    at Query.Sequence._packetToError (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:307:12)
    --------------------
    at Protocol._enqueue (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/Connection.js:198:25)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at Connection.query (internal/util.js:296:12)
    at Object.writeCurrentSemester (/Users/leonmba/gitstuff/codedatasurvey/db.js:81:23)
    at /Users/leonmba/gitstuff/codedatasurvey/index.js:35:51
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3",
  sqlState: '42000',
  index: 0,
  sql: 'INSERT INTO fs20_modules(\n' +
    '        student_id,\n' +
    '        semester_module_lp_id\n' +
    '    ) VALUES ;'
}
[ERROR] -  Error: Request failed with status code 500
    at createError (/Users/leonmba/gitstuff/codedatasurvey/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/leonmba/gitstuff/codedatasurvey/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/leonmba/gitstuff/codedatasurvey/node_modules/axios/lib/adapters/http.js:244:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: 'https://api.app.code.berlin/graphql',
    method: 'post',
    data: `{"query":"query {\\n        myStudies {\\n            shortCode  # eg SE_36_Fall_2019. We don't need this but I think it's good to have in case we can't work with the semesterModule id later\\n            assessments {\\n                assessmentStatus  # present, absent, etc\\n                assessmentStyle  # standard, alternative, etc\\n                examinationForms  # oral, written, etc\\n                proposalText\\n                grade\\n                assessmentProtocol\\n                internalNotes\\n                externalFeedback\\n                attempt\\n                earlyAssessmentProposal\\n                assessmentType  # normal, reassessment, level up, etc\\n                project {\\n                    id\\n                }\\n                semesterModule {\\n                    id\\n                }\\n            }\\n        }\\n    }"}`,
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=utf-8',
      Authorization: `[ERROR] -  Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3     at Query.Sequence._packetToError (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)     at Query.ErrorPacket (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)     at Protocol._parsePacket (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Protocol.js:291:23)     at Parser._parsePacket (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Parser.js:433:10)     at Parser.write (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Parser.js:43:10)     at Protocol.write (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Protocol.js:38:16)     at Socket.<anonymous> (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/Connection.js:88:28)     at Socket.<anonymous> (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/Connection.js:526:10)     at Socket.emit (events.js:314:20)     at addChunk (_stream_readable.js:307:12)     --------------------     at Protocol._enqueue (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Protocol.js:144:48)     at Connection.query (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/Connection.js:198:25)     at internal/util.js:297:30     at new Promise (<anonymous>)     at Connection.query (internal/util.js:296:12)     at Object.writeCurrentSemester (/Users/leonmba/gitstuff/codedatasurvey/db.js:81:23)     at /Users/leonmba/gitstuff/codedatasurvey/index.js:35:51     at processTicksAndRejections (internal/process/task_queues.js:93:5) {   code: 'ER_PARSE_ERROR',   errno: 1064,   sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3",   sqlState: '42000',   index: 0,   sql: 'INSERT INTO fs20_modules(\\n' +     '        student_id,\\n' +     '        semester_module_lp_id\\n' +     '    ) VALUES ;' }`,
      'User-Agent': 'axios/0.20.0',
      'Content-Length': 865
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.app.code.berlin',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.app.code.berlin',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 163,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /graphql HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json;charset=utf-8\r\n' +
      `Authorization: [ERROR] -  Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3     at Query.Sequence._packetToError (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)     at Query.ErrorPacket (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)     at Protocol._parsePacket (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Protocol.js:291:23)     at Parser._parsePacket (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Parser.js:433:10)     at Parser.write (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Parser.js:43:10)     at Protocol.write (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Protocol.js:38:16)     at Socket.<anonymous> (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/Connection.js:88:28)     at Socket.<anonymous> (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/Connection.js:526:10)     at Socket.emit (events.js:314:20)     at addChunk (_stream_readable.js:307:12)     --------------------     at Protocol._enqueue (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Protocol.js:144:48)     at Connection.query (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/Connection.js:198:25)     at internal/util.js:297:30     at new Promise (<anonymous>)     at Connection.query (internal/util.js:296:12)     at Object.writeCurrentSemester (/Users/leonmba/gitstuff/codedatasurvey/db.js:81:23)     at /Users/leonmba/gitstuff/codedatasurvey/index.js:35:51     at processTicksAndRejections (internal/process/task_queues.js:93:5) {   code: 'ER_PARSE_ERROR',   errno: 1064,   sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3",   sqlState: '42000',   index: 0,   sql: 'INSERT INTO fs20_modules(\\n' +     '        student_id,\\n' +     '        semester_module_lp_id\\n' +     '    ) VALUES ;' }\r\n` +
      'User-Agent: axios/0.20.0\r\n' +
      'Content-Length: 865\r\n' +
      'Host: api.app.code.berlin\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/graphql',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.app.code.berlin/graphql',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.app.code.berlin',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 865,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.app.code.berlin/graphql',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: {
      date: 'Fri, 25 Sep 2020 10:06:47 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '145',
      connection: 'close',
      'x-amzn-requestid': '77514dc1-041f-4833-be1c-1c6568cbfaec',
      'x-dns-prefetch-control': 'off',
      'x-xss-protection': '1; mode=block',
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      'x-frame-options': 'SAMEORIGIN',
      'x-amzn-remapped-content-length': '145',
      'x-download-options': 'noopen',
      'x-amz-apigw-id': 'TasguHCqFiAFTXA=',
      vary: 'Origin',
      'x-content-type-options': 'nosniff',
      etag: 'W/"91-yDA4GfEhMGgPNnJsQ+7uKaxszQY"',
      'x-amzn-trace-id': 'Root=1-5f6dc137-48706c002e404c2819e82c78;Sampled=0',
      'access-control-allow-credentials': 'true'
    },
    config: {
      url: 'https://api.app.code.berlin/graphql',
      method: 'post',
      data: `{"query":"query {\\n        myStudies {\\n            shortCode  # eg SE_36_Fall_2019. We don't need this but I think it's good to have in case we can't work with the semesterModule id later\\n            assessments {\\n                assessmentStatus  # present, absent, etc\\n                assessmentStyle  # standard, alternative, etc\\n                examinationForms  # oral, written, etc\\n                proposalText\\n                grade\\n                assessmentProtocol\\n                internalNotes\\n                externalFeedback\\n                attempt\\n                earlyAssessmentProposal\\n                assessmentType  # normal, reassessment, level up, etc\\n                project {\\n                    id\\n                }\\n                semesterModule {\\n                    id\\n                }\\n            }\\n        }\\n    }"}`,
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /graphql HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json;charset=utf-8\r\n' +
        `Authorization: [ERROR] -  Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3     at Query.Sequence._packetToError (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)     at Query.ErrorPacket (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)     at Protocol._parsePacket (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Protocol.js:291:23)     at Parser._parsePacket (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Parser.js:433:10)     at Parser.write (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Parser.js:43:10)     at Protocol.write (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Protocol.js:38:16)     at Socket.<anonymous> (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/Connection.js:88:28)     at Socket.<anonymous> (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/Connection.js:526:10)     at Socket.emit (events.js:314:20)     at addChunk (_stream_readable.js:307:12)     --------------------     at Protocol._enqueue (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/protocol/Protocol.js:144:48)     at Connection.query (/Users/leonmba/gitstuff/codedatasurvey/node_modules/mysql/lib/Connection.js:198:25)     at internal/util.js:297:30     at new Promise (<anonymous>)     at Connection.query (internal/util.js:296:12)     at Object.writeCurrentSemester (/Users/leonmba/gitstuff/codedatasurvey/db.js:81:23)     at /Users/leonmba/gitstuff/codedatasurvey/index.js:35:51     at processTicksAndRejections (internal/process/task_queues.js:93:5) {   code: 'ER_PARSE_ERROR',   errno: 1064,   sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3",   sqlState: '42000',   index: 0,   sql: 'INSERT INTO fs20_modules(\\n' +     '        student_id,\\n' +     '        semester_module_lp_id\\n' +     '    ) VALUES ;' }\r\n` +
        'User-Agent: axios/0.20.0\r\n' +
        'Content-Length: 865\r\n' +
        'Host: api.app.code.berlin\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/graphql',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.app.code.berlin',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { errors: [Array] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

```

**Comment by leonrudowicz** [comment]
https://github.com/studyjourney/codedatasurvey/blob/2ab8c1ed1f83a5509ec72fb96f9e567490d8ed6b/index.js#L35

Seems like studentID does not contain the authorization header, but the error code of the previously failed sql

**Comment by leonrudowicz** [comment]
> https://github.com/studyjourney/codedatasurvey/blob/2ab8c1ed1f83a5509ec72fb96f9e567490d8ed6b/index.js#L35
> 
> Seems like studentID does not contain the authorization header, but the error code of the previously failed sql

thats bs btw ... maybe token gets overwritten somehow

**Comment by leonrudowicz** [comment]
Fixed with https://github.com/studyjourney/codedatasurvey/commit/7a13680eaca7dee2ba384e516a1b15779035c26d
